[parity]
chain = "chain-spec.json"
base_path = "./chaindata"
keys_path = "./keys"

[network]
port = 30300

[rpc]
apis = ["web3","eth","net", "parity", "traces"]
processing_threads = 200
server_threads = 200
interface="all"
cors=["all"]

[websockets]
disable = false
max_connections = 1000
port = 8546
interface = "all"
origins = ["all"]
apis = ["web3","eth","net","parity", "pubsub", "traces"]
hosts = ["all"]

[footprint]
tracing = "on"
pruning = "archive"
fat_db = "on"