[parity]
chain = "chain-spec.json"
base_path = "./chaindata"
keys_path = "./keys"

[network]
port = 30300

[rpc]
disable = false
port= 8545
apis = ["web3","eth","net", "parity",  "traces"]
cors=["all"]

[websockets]
disable = false
port = 8546
interface = "all"
origins = ["all"]
apis = ["web3","eth","net","parity", "pubsub", "traces"]
hosts = ["all"]

[footprint]
tracing = "on"
pruning = "archive"
fat_db = "on"